spring:
  application:
    name: library.management
  datasource:
    url: jdbc:h2:file:/data/demo2
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
server:
  port: 8080